const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
]

const DEMO_VEHICLES = ['DEMO-VEH-001', 'DEMO-VEH-002', 'DEMO-VEH-003']
const DEMO_DRIVERS = ['Demo Driver Alpha', 'Demo Driver Beta', 'Sample Driver Gamma']
const DEMO_PARTIES = ['Northstar Demo Mobility', 'Bluebird Sample Tours', 'Sunrise Demo Corporate']
const DEMO_VENDORS = ['Demo Fuel Vendor', 'Sample Parts Vendor', 'Demo Service Vendor']

const vehicleFields = [
  {
    title: 'Vehicle details',
    description: 'Add the vehicle identity, assigned driver, and fleet classification.',
    fields: [
      {
        name: 'vehiclePhoto',
        label: 'Vehicle Photo',
        type: 'file',
        accept: 'image/*',
        full: true,
        help: 'Upload a clear JPG, PNG, or WEBP image of the vehicle.',
      },
      {
        name: 'driverName',
        label: 'Driver Name',
        type: 'select',
        options: DEMO_DRIVERS,
        placeholder: 'Select driver',
      },
      {
        name: 'registrationNumber',
        label: 'Registration Number',
        type: 'text',
        required: true,
        placeholder: 'Enter registration number',
      },
      {
        name: 'chassisNumber',
        label: 'Chasis Number',
        type: 'text',
        placeholder: 'Enter chassis number',
      },
      {
        name: 'engineNumber',
        label: 'Engine Number',
        type: 'text',
        placeholder: 'Enter engine number',
      },
      {
        name: 'manufactureYear',
        label: 'Manufacture Year',
        type: 'number',
        placeholder: 'Enter manufacture year',
      },
      {
        name: 'vehicleMake',
        label: 'Vehicle Make',
        type: 'select',
        required: true,
        placeholder: 'Select vehicle make',
        options: [
          'Maruti Suzuki',
          'Hyundai',
          'Tata',
          'Toyota',
          'Kia',
          'Skoda',
          'Mercedes',
          'Volkswagen',
          'Honda',
          'Renault',
          'Nissan',
          'Ford',
          'Mahindra',
        ],
      },
      {
        name: 'vehicleModel',
        label: 'Vehicle Model',
        type: 'text',
        required: true,
        placeholder: 'Enter vehicle model',
      },
      {
        name: 'vehicleType',
        label: 'Vehicle Type',
        type: 'select',
        required: true,
        placeholder: 'Select vehicle type',
        options: ['Sedan', 'SUV', 'MPV/MUV', 'Van'],
      },
      {
        name: 'vehicleGroup',
        label: 'Vehicle Group',
        type: 'select',
        placeholder: 'Select vehicle group',
        options: ['T-Permit', 'Private'],
      },
    ],
  },
  {
    title: 'Registration and ownership',
    description: 'Record registration, capacity, ownership, and fuel information.',
    fields: [
      {
        name: 'registrationState',
        label: 'Registration State',
        type: 'select',
        options: INDIAN_STATES,
        placeholder: 'Select state',
      },
      { name: 'registrationDate', label: 'Registration Date', type: 'date' },
      { name: 'registrationUpto', label: 'Registration Upto', type: 'date' },
      {
        name: 'currentOdometer',
        label: 'Vehicle Current Odometer',
        type: 'number',
        placeholder: 'Enter current odometer reading',
      },
      {
        name: 'vehicleColor',
        label: 'Vehicle Color',
        type: 'text',
        placeholder: 'Enter vehicle color',
      },
      {
        name: 'seatingCapacity',
        label: 'Seating Capacity',
        type: 'number',
        placeholder: 'Enter seating capacity',
      },
      {
        name: 'vehicleOwnership',
        label: 'Vehicle Ownership',
        type: 'select',
        options: ['Owned', 'Rented', 'Leased'],
        placeholder: 'Select vehicle ownership',
      },
      {
        name: 'fuelType',
        label: 'Fuel Type',
        type: 'select',
        options: ['Petrol', 'Diesel', 'Petrol/CNG', 'Electric'],
        placeholder: 'Select fuel type',
      },
      {
        name: 'fuelCapacity',
        label: 'Fuel Capacity',
        type: 'number',
        placeholder: 'Enter capacity in litres',
      },
      {
        name: 'engineOilCapacity',
        label: 'Engine Oil Capacity',
        type: 'number',
        placeholder: 'Enter capacity in litres',
      },
    ],
  },
  {
    title: 'Vehicle documents',
    description: 'Store compliance documents and their validity dates.',
    fields: [
      {
        name: 'rcBook',
        label: 'RC Book',
        type: 'file',
        accept: '.pdf,image/*',
      },
      {
        name: 'insurance',
        label: 'Insurance',
        type: 'file',
        accept: '.pdf,image/*',
      },
      { name: 'insuranceValidFrom', label: 'Insurance Valid Frm', type: 'date' },
      { name: 'insuranceValidUpto', label: 'Insurance Valid Upto', type: 'date' },
      { name: 'puc', label: 'PUC', type: 'file', accept: '.pdf,image/*' },
      { name: 'pucValidFrom', label: 'PUC Valid Frm', type: 'date' },
      { name: 'pucValidUpto', label: 'PUC Valid Upto', type: 'date' },
    ],
  },
]

const driverFields = [
  {
    title: 'Driver details',
    description: 'Enter employment and personal information for the driver.',
    fields: [
      {
        name: 'driverPhoto',
        label: 'Driver Photo',
        type: 'file',
        accept: 'image/*',
        full: true,
      },
      {
        name: 'employeeNumber',
        label: 'Emp No.',
        type: 'text',
        required: true,
        placeholder: 'Enter employee number',
      },
      { name: 'joiningDate', label: 'Joining Date', type: 'date', required: true },
      {
        name: 'firstName',
        label: 'First Name',
        type: 'text',
        required: true,
        placeholder: 'Enter first name',
      },
      {
        name: 'lastName',
        label: 'Last Name',
        type: 'text',
        required: true,
        placeholder: 'Enter last name',
      },
      {
        name: 'fatherName',
        label: 'Father Name',
        type: 'text',
        placeholder: "Enter father's name",
      },
      { name: 'dateOfBirth', label: 'Date of Birth', type: 'date' },
      {
        name: 'mobileNumber',
        label: 'Mobile No.',
        type: 'tel',
        required: true,
        placeholder: 'Enter mobile number',
      },
      {
        name: 'qualification',
        label: 'Qualification',
        type: 'text',
        placeholder: 'Enter qualification',
      },
      {
        name: 'bloodGroup',
        label: 'Blood Group',
        type: 'select',
        placeholder: 'Select blood group',
        options: ['O+', 'O-', 'A+', 'A-', 'B+', 'B-', 'AB+', 'AB-'],
      },
      {
        name: 'language',
        label: 'Language',
        type: 'select',
        placeholder: 'Select language',
        options: [
          'Hindi',
          'Marathi',
          'English',
          'Gujarati',
          'Tamil',
          'Telugu',
          'Punjabi',
          'Kannada',
          'Malayalam',
          'Odia',
        ],
      },
      {
        name: 'groupService',
        label: 'Group Service',
        type: 'select',
        placeholder: 'Select group service',
        options: ['Passenger Car', 'Company Car', 'Passenger & Company Both'],
      },
      {
        name: 'salaryType',
        label: 'Salary Type',
        type: 'select',
        placeholder: 'Select salary type',
        options: ['Month Wise', 'Day Wise'],
      },
      {
        name: 'salary',
        label: 'Salary',
        type: 'number',
        placeholder: 'Enter salary amount',
      },
    ],
  },
  {
    title: 'Contact and address',
    description: 'Add communication details and the driver address.',
    fields: [
      {
        name: 'email',
        label: 'Email Id',
        type: 'email',
        placeholder: 'name@example.com',
      },
      {
        name: 'alternateNumber',
        label: 'Home|Alternate Number',
        type: 'tel',
        placeholder: 'Enter alternate number',
      },
      {
        name: 'location',
        label: 'Location',
        type: 'text',
        required: true,
        placeholder: 'Enter location',
      },
      {
        name: 'address',
        label: 'Address',
        type: 'textarea',
        full: true,
        placeholder: 'Enter complete address',
      },
      {
        name: 'state',
        label: 'State',
        type: 'select',
        options: INDIAN_STATES,
        placeholder: 'Select state',
      },
      { name: 'city', label: 'City', type: 'text', placeholder: 'Enter city' },
      {
        name: 'postalCode',
        label: 'Postal',
        type: 'text',
        placeholder: 'Enter postal code',
      },
    ],
  },
  {
    title: 'Bank information',
    description: 'Maintain salary payment details.',
    fields: [
      { name: 'bankName', label: 'Bank Name', type: 'text', placeholder: 'Enter bank name' },
      {
        name: 'accountHolderName',
        label: 'Bank Account Holder Name',
        type: 'text',
        placeholder: 'Enter account holder name',
      },
      {
        name: 'accountNumber',
        label: 'Bank Account Number',
        type: 'text',
        placeholder: 'Enter account number',
      },
      {
        name: 'ifscCode',
        label: 'Bank IFSC',
        type: 'text',
        placeholder: 'Enter IFSC code',
      },
    ],
  },
  {
    title: 'References and documents',
    description: 'Add an emergency reference and driver identity documents.',
    fields: [
      {
        name: 'referenceName',
        label: 'Reference Name',
        type: 'text',
        placeholder: 'Enter reference name',
      },
      {
        name: 'referenceNumber',
        label: 'Reference Number',
        type: 'tel',
        placeholder: 'Enter reference number',
      },
      {
        name: 'drivingLicence',
        label: 'Driving Licence',
        type: 'file',
        accept: '.pdf,image/*',
      },
      {
        name: 'licenceState',
        label: 'Driving Licence State',
        type: 'select',
        options: INDIAN_STATES,
        placeholder: 'Select state',
      },
      { name: 'licenceValidUpto', label: 'Driving Licence Valid Upto', type: 'date' },
      {
        name: 'aadhaarCard',
        label: 'Adhar Card',
        type: 'file',
        accept: '.pdf,image/*',
      },
      {
        name: 'panCard',
        label: 'Pancard Card',
        type: 'file',
        accept: '.pdf,image/*',
      },
    ],
  },
]

export const crmModules = {
  vehicles: {
    key: 'vehicles',
    path: '/vehicles',
    singular: 'Vehicle',
    plural: 'Vehicles',
    description: 'Manage fleet vehicles, registration details, documents, and availability.',
    addLabel: 'Add Vehicle',
    view: true,
    searchable: [
      'registrationNumber',
      'vehicleMake',
      'vehicleModel',
      'driverName',
      'documentStatus',
      'status',
    ],
    columns: [
      { key: 'registrationNumber', label: 'Vehicle Number', primary: true },
      { key: 'vehicleModel', label: 'Vehicle', secondaryKey: 'vehicleMake' },
      { key: 'driverName', label: 'Driver' },
      { key: 'kmsDone', label: "Km's Done", format: 'number' },
      { key: 'documentStatus', label: 'Document Status', format: 'status' },
      { key: 'lastTrip', label: 'Last Trip', format: 'date' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    sections: vehicleFields,
    seed: [
      {
        id: 'vehicle-demo-1',
        registrationNumber: 'DEMO-VEH-001',
        vehicleMake: 'Toyota',
        vehicleModel: 'Innova Crysta',
        vehicleType: 'MPV/MUV',
        vehicleGroup: 'T-Permit',
        driverName: 'Demo Driver Alpha',
        chassisNumber: 'DEMO-CHASSIS-001',
        engineNumber: 'DEMO-ENGINE-001',
        manufactureYear: 2023,
        registrationState: 'Maharashtra',
        registrationDate: '2023-02-12',
        registrationUpto: '2038-02-11',
        currentOdometer: 48210,
        kmsDone: 3120,
        vehicleColor: 'White',
        seatingCapacity: 7,
        vehicleOwnership: 'Owned',
        fuelType: 'Diesel',
        fuelCapacity: 55,
        engineOilCapacity: 6,
        insuranceValidFrom: '2026-02-01',
        insuranceValidUpto: '2027-01-31',
        pucValidFrom: '2026-04-01',
        pucValidUpto: '2027-03-31',
        documentStatus: 'Complete',
        lastTrip: '2026-09-28',
        status: 'Active',
      },
      {
        id: 'vehicle-demo-2',
        registrationNumber: 'DEMO-VEH-002',
        vehicleMake: 'Maruti Suzuki',
        vehicleModel: 'Dzire',
        vehicleType: 'Sedan',
        vehicleGroup: 'Private',
        driverName: 'Demo Driver Beta',
        chassisNumber: 'DEMO-CHASSIS-002',
        engineNumber: 'DEMO-ENGINE-002',
        manufactureYear: 2024,
        registrationState: 'Maharashtra',
        registrationDate: '2024-06-18',
        registrationUpto: '2039-06-17',
        currentOdometer: 23890,
        kmsDone: 1840,
        vehicleColor: 'Silver',
        seatingCapacity: 5,
        vehicleOwnership: 'Leased',
        fuelType: 'Petrol/CNG',
        fuelCapacity: 37,
        engineOilCapacity: 4,
        insuranceValidFrom: '2026-06-01',
        insuranceValidUpto: '2027-05-31',
        pucValidFrom: '2026-07-01',
        pucValidUpto: '2027-06-30',
        documentStatus: 'Renewal Due',
        lastTrip: '2026-10-01',
        status: 'Available',
      },
    ],
  },

  drivers: {
    key: 'drivers',
    path: '/drivers',
    singular: 'Driver',
    plural: 'Drivers',
    description: 'Maintain driver profiles, employment details, documents, and contacts.',
    addLabel: 'Add Driver',
    view: true,
    searchable: ['employeeNumber', 'firstName', 'lastName', 'mobileNumber', 'location', 'email'],
    columns: [
      { key: 'joiningDate', label: 'Joining Date', format: 'date' },
      { key: 'employeeNumber', label: 'Emp No.', primary: true },
      { key: 'firstName', label: 'Name', secondaryKey: 'lastName' },
      { key: 'mobileNumber', label: 'Contact No.' },
      { key: 'location', label: 'Location' },
      { key: 'email', label: 'Email ID' },
    ],
    sections: driverFields,
    seed: [
      {
        id: 'driver-demo-1',
        employeeNumber: 'DEMO-EMP-001',
        joiningDate: '2024-04-15',
        firstName: 'Demo Driver',
        lastName: 'Alpha',
        fatherName: 'Sample Parent Alpha',
        dateOfBirth: '1990-08-12',
        mobileNumber: '+91 00000 00001',
        qualification: 'Higher Secondary',
        bloodGroup: 'O+',
        language: 'Hindi',
        groupService: 'Passenger & Company Both',
        salaryType: 'Month Wise',
        salary: 28000,
        email: 'driver.alpha@example.com',
        alternateNumber: '+91 00000 10001',
        location: 'Mumbai Demo Zone',
        address: '101 Demo Residency, Sample Road',
        state: 'Maharashtra',
        city: 'Mumbai',
        postalCode: '400000',
        bankName: 'Demo Cooperative Bank',
        accountHolderName: 'Demo Driver Alpha',
        accountNumber: 'DEMO-ACCOUNT-001',
        ifscCode: 'DEMO0000001',
        referenceName: 'Sample Reference Alpha',
        referenceNumber: '+91 00000 20001',
        licenceState: 'Maharashtra',
        licenceValidUpto: '2029-08-11',
      },
      {
        id: 'driver-demo-2',
        employeeNumber: 'DEMO-EMP-002',
        joiningDate: '2025-01-08',
        firstName: 'Demo Driver',
        lastName: 'Beta',
        fatherName: 'Sample Parent Beta',
        dateOfBirth: '1993-11-21',
        mobileNumber: '+91 00000 00002',
        qualification: 'Graduate',
        bloodGroup: 'B+',
        language: 'Marathi',
        groupService: 'Passenger Car',
        salaryType: 'Day Wise',
        salary: 1200,
        email: 'driver.beta@example.com',
        alternateNumber: '+91 00000 10002',
        location: 'Pune Sample Zone',
        address: '202 Sample Enclave, Demo Avenue',
        state: 'Maharashtra',
        city: 'Pune',
        postalCode: '411000',
        bankName: 'Sample Urban Bank',
        accountHolderName: 'Demo Driver Beta',
        accountNumber: 'DEMO-ACCOUNT-002',
        ifscCode: 'DEMO0000002',
        referenceName: 'Sample Reference Beta',
        referenceNumber: '+91 00000 20002',
        licenceState: 'Maharashtra',
        licenceValidUpto: '2031-11-20',
      },
    ],
  },

  parties: {
    key: 'parties',
    path: '/parties',
    singular: 'Party',
    plural: 'Parties',
    description: 'Manage corporate customers, contacts, rates, and billing details.',
    addLabel: 'Add Party',
    view: false,
    searchable: ['corporateName', 'contactName', 'phoneNumber', 'location', 'gstNumber'],
    columns: [
      { key: 'registeredDate', label: 'Registered Date', format: 'date' },
      { key: 'corporateName', label: 'Corporate Name', primary: true },
      { key: 'contactName', label: 'Contact Name' },
      { key: 'phoneNumber', label: 'Number' },
      { key: 'location', label: 'Location' },
      { key: 'status', label: 'Status', format: 'status' },
    ],
    sections: [
      {
        title: 'Party details',
        description: 'Enter the organisation and primary contact information.',
        fields: [
          {
            name: 'corporateName',
            label: 'Corporate Name',
            type: 'text',
            required: true,
            placeholder: 'Enter corporate name',
          },
          {
            name: 'contactName',
            label: 'Contact Person Name',
            type: 'text',
            required: true,
            placeholder: 'Enter contact person name',
          },
          {
            name: 'phoneNumber',
            label: 'Phone No.',
            type: 'tel',
            required: true,
            placeholder: 'Enter phone number',
          },
          {
            name: 'alternateNumber',
            label: 'Alternate Number',
            type: 'tel',
            placeholder: 'Enter alternate number',
          },
          {
            name: 'email',
            label: 'Email Id',
            type: 'email',
            placeholder: 'billing@example.com',
          },
          {
            name: 'address',
            label: 'Address',
            type: 'textarea',
            full: true,
            placeholder: 'Enter complete address',
          },
          {
            name: 'location',
            label: 'Location',
            type: 'text',
            required: true,
            placeholder: 'Enter location',
          },
        ],
      },
      {
        title: 'Commercial details',
        description: 'Add tax, rate, and internal notes for this party.',
        fields: [
          {
            name: 'gstNumber',
            label: 'Gst Number',
            type: 'text',
            placeholder: 'Enter GST number',
          },
          {
            name: 'perKmRate',
            label: 'Per Km Rate',
            type: 'number',
            placeholder: 'Enter rate per kilometre',
          },
          {
            name: 'remark',
            label: 'Remark',
            type: 'textarea',
            full: true,
            placeholder: 'Add a remark',
          },
        ],
      },
    ],
    seed: [
      {
        id: 'party-demo-1',
        registeredDate: '2026-01-12',
        corporateName: 'Northstar Demo Mobility',
        contactName: 'Demo Contact Alpha',
        phoneNumber: '+91 00000 30001',
        alternateNumber: '+91 00000 31001',
        email: 'accounts@northstar-demo.example.com',
        address: 'Demo Business Park, Sample Road',
        location: 'Mumbai Demo Zone',
        gstNumber: 'DEMO-GST-0001',
        perKmRate: 24,
        remark: 'Fictional corporate account used for interface previews.',
        status: 'Active',
      },
      {
        id: 'party-demo-2',
        registeredDate: '2026-03-06',
        corporateName: 'Bluebird Sample Tours',
        contactName: 'Demo Contact Beta',
        phoneNumber: '+91 00000 30002',
        alternateNumber: '+91 00000 31002',
        email: 'billing@bluebird-sample.example.com',
        address: 'Sample Trade Centre, Demo Avenue',
        location: 'Pune Sample Zone',
        gstNumber: 'DEMO-GST-0002',
        perKmRate: 22,
        remark: 'Fictional travel partner record.',
        status: 'Active',
      },
    ],
  },

  tripsRegular: {
    key: 'tripsRegular',
    path: '/trips/regular',
    singular: 'Regular Trip',
    plural: 'Regular Trips',
    description: 'Plan regular vehicle assignments, routes, dates, and advances.',
    addLabel: 'Add Trip',
    view: false,
    searchable: [
      'vehicleNumber',
      'driverName',
      'clientName',
      'number',
      'pickupAddress',
      'dropAddress',
      'bookingReference',
    ],
    columns: [
      { key: 'startDate', label: 'Trip Date', format: 'date' },
      { key: 'vehicleNumber', label: 'Vehicle Number', primary: true },
      { key: 'driverName', label: 'Driver Name' },
      { key: 'clientName', label: 'Client Name' },
      { key: 'number', label: 'Number' },
      { key: 'endDate', label: 'End Date', format: 'date' },
      { key: 'pickupAddress', label: 'Pickup' },
      { key: 'dropAddress', label: 'Drop' },
      { key: 'advanceAmount', label: 'Advance', format: 'currency' },
    ],
    sections: [
      {
        title: 'Trip details',
        description: 'Choose the vehicle, customer, schedule, and route.',
        fields: [
          {
            name: 'vehicleNumber',
            label: 'Vehicle Number',
            type: 'select',
            required: true,
            placeholder: 'Select vehicle',
            options: DEMO_VEHICLES,
          },
          {
            name: 'clientName',
            label: 'Client Name',
            type: 'text',
            required: true,
            placeholder: 'Enter client name',
          },
          {
            name: 'number',
            label: 'Number',
            type: 'tel',
            required: true,
            placeholder: 'Enter contact number',
          },
          { name: 'startDate', label: 'Start Date', type: 'date', required: true },
          { name: 'startTime', label: 'Time', type: 'time', required: true },
          { name: 'endDate', label: 'End Date', type: 'date', required: true },
          { name: 'endTime', label: 'Time', type: 'time', required: true },
          {
            name: 'pickupAddress',
            label: 'Pickup Address',
            type: 'textarea',
            required: true,
            placeholder: 'Enter pickup address',
          },
          {
            name: 'dropAddress',
            label: 'Drop Address',
            type: 'textarea',
            required: true,
            placeholder: 'Enter drop address',
          },
        ],
      },
      {
        title: 'Booking and billing',
        description: 'Add the booking reference, rate, advance, and notes.',
        fields: [
          {
            name: 'bookingReference',
            label: 'Booking Reference',
            type: 'text',
            placeholder: 'Enter booking reference',
          },
          {
            name: 'email',
            label: 'Email Id',
            type: 'email',
            placeholder: 'client@example.com',
          },
          {
            name: 'perKmRate',
            label: 'Per Km Rate',
            type: 'number',
            placeholder: 'Enter rate per kilometre',
          },
          {
            name: 'advanceGiven',
            label: 'Advance Given',
            type: 'radio',
            options: ['Yes', 'No'],
          },
          {
            name: 'advanceAmount',
            label: 'Advance Amount',
            type: 'number',
            placeholder: 'Enter advance amount',
          },
          {
            name: 'remark',
            label: 'Remark',
            type: 'textarea',
            full: true,
            placeholder: 'Add trip notes',
          },
        ],
      },
    ],
    seed: [
      {
        id: 'regular-trip-demo-1',
        vehicleNumber: 'DEMO-VEH-001',
        driverName: 'Demo Driver Alpha',
        clientName: 'Demo Traveller Alpha',
        number: '+91 00000 40001',
        startDate: '2026-10-08',
        startTime: '08:30',
        endDate: '2026-10-10',
        endTime: '19:00',
        pickupAddress: 'Demo Pickup Point, Mumbai',
        dropAddress: 'Sample Drop Point, Pune',
        bookingReference: 'DEMO-REG-001',
        email: 'traveller.alpha@example.com',
        perKmRate: 24,
        advanceGiven: 'Yes',
        advanceAmount: 3500,
        remark: 'Fictional outstation trip for preview purposes.',
      },
      {
        id: 'regular-trip-demo-2',
        vehicleNumber: 'DEMO-VEH-002',
        driverName: 'Demo Driver Beta',
        clientName: 'Demo Traveller Beta',
        number: '+91 00000 40002',
        startDate: '2026-10-12',
        startTime: '06:15',
        endDate: '2026-10-12',
        endTime: '22:00',
        pickupAddress: 'Sample Corporate Park, Mumbai',
        dropAddress: 'Demo Convention Centre, Nashik',
        bookingReference: 'DEMO-REG-002',
        email: 'traveller.beta@example.com',
        perKmRate: 22,
        advanceGiven: 'No',
        advanceAmount: 0,
        remark: 'Fictional same-day booking.',
      },
    ],
  },

  tripsPickupDrop: {
    key: 'tripsPickupDrop',
    path: '/trips/pickup-drop',
    singular: 'Pickup/Drop Trip',
    plural: 'Pickup/Drop Trips',
    description: 'Schedule point-to-point pickups and drops with rates and advances.',
    addLabel: 'Add Pickup/Drop Trip',
    view: false,
    searchable: [
      'vehicleNumber',
      'driverName',
      'partyName',
      'number',
      'pickupOrDrop',
      'pickupDropPoint',
    ],
    columns: [
      { key: 'tripDate', label: 'Trip Date', format: 'date' },
      { key: 'tripTime', label: 'Time' },
      { key: 'vehicleNumber', label: 'Vehicle Number', primary: true },
      { key: 'driverName', label: 'Driver Name' },
      { key: 'partyName', label: 'Party Name' },
      { key: 'number', label: 'Number' },
      { key: 'advance', label: 'Advance', format: 'currency' },
    ],
    sections: [
      {
        title: 'Pickup or drop details',
        description: 'Choose the vehicle, party, schedule, and service point.',
        fields: [
          {
            name: 'vehicleNumber',
            label: 'Vehicle Number',
            type: 'select',
            required: true,
            placeholder: 'Select vehicle',
            options: DEMO_VEHICLES,
          },
          { name: 'tripDate', label: 'Date', type: 'date', required: true },
          { name: 'tripTime', label: 'Time', type: 'time', required: true },
          {
            name: 'partyName',
            label: 'Party Name',
            type: 'select',
            required: true,
            placeholder: 'Select party',
            options: DEMO_PARTIES,
          },
          {
            name: 'number',
            label: 'Number',
            type: 'tel',
            required: true,
            placeholder: 'Enter contact number',
          },
          {
            name: 'email',
            label: 'Email Id',
            type: 'email',
            placeholder: 'client@example.com',
          },
          {
            name: 'pickupOrDrop',
            label: 'Pickup or Drop',
            type: 'select',
            required: true,
            placeholder: 'Select service',
            options: ['Pickup', 'Drop'],
          },
          {
            name: 'pickupDropPoint',
            label: 'Pickup or Drop Point',
            type: 'textarea',
            required: true,
            full: true,
            placeholder: 'Enter pickup or drop point',
          },
        ],
      },
      {
        title: 'Distance and billing',
        description: 'Record the agreed rate, distance, amount, and advance.',
        fields: [
          { name: 'rate', label: 'Rate', type: 'number', placeholder: 'Enter rate' },
          {
            name: 'totalKm',
            label: 'Total Km',
            type: 'number',
            placeholder: 'Enter total kilometres',
          },
          {
            name: 'totalRate',
            label: 'Total Rate',
            type: 'number',
            readOnly: true,
            help: 'Calculated from the entered rate and total kilometres.',
          },
          {
            name: 'advance',
            label: 'Advance',
            type: 'number',
            placeholder: 'Enter advance amount',
          },
          {
            name: 'remark',
            label: 'Remark',
            type: 'textarea',
            full: true,
            placeholder: 'Add trip notes',
          },
        ],
      },
    ],
    seed: [
      {
        id: 'pickup-drop-demo-1',
        vehicleNumber: 'DEMO-VEH-002',
        driverName: 'Demo Driver Beta',
        tripDate: '2026-10-06',
        tripTime: '05:45',
        partyName: 'Northstar Demo Mobility',
        number: '+91 00000 50001',
        email: 'travel@northstar-demo.example.com',
        rate: 56.25,
        pickupOrDrop: 'Pickup',
        pickupDropPoint: 'Demo Airport Terminal to Sample Business Park',
        totalKm: 32,
        totalRate: 1800,
        advance: 500,
        remark: 'Fictional airport pickup.',
      },
      {
        id: 'pickup-drop-demo-2',
        vehicleNumber: 'DEMO-VEH-003',
        driverName: 'Sample Driver Gamma',
        tripDate: '2026-10-09',
        tripTime: '21:30',
        partyName: 'Bluebird Sample Tours',
        number: '+91 00000 50002',
        email: 'ops@bluebird-sample.example.com',
        rate: 84,
        pickupOrDrop: 'Drop',
        pickupDropPoint: 'Sample Hotel to Demo Railway Terminus',
        totalKm: 25,
        totalRate: 2100,
        advance: 0,
        remark: 'Fictional late-evening drop.',
      },
    ],
  },

  vendors: {
    key: 'vendors',
    path: '/vendors',
    singular: 'Vendor',
    plural: 'Vendors',
    description: 'Maintain fuel, parts, and service vendor records and bank details.',
    addLabel: 'Add Vendor',
    view: false,
    searchable: ['vendorName', 'vendorNumber', 'vendorType', 'gstNumber', 'city'],
    columns: [
      { key: 'vendorName', label: 'Vendor Name', primary: true },
      { key: 'vendorNumber', label: 'Number' },
      { key: 'vendorType', label: 'Type', format: 'status' },
      { key: 'gstNumber', label: 'GST Number' },
      { key: 'city', label: 'City' },
    ],
    sections: [
      {
        title: 'Vendor details',
        description: 'Enter vendor contact, category, and address information.',
        fields: [
          {
            name: 'vendorName',
            label: 'Vendor Name',
            type: 'text',
            required: true,
            placeholder: 'Enter vendor name',
          },
          {
            name: 'vendorNumber',
            label: 'Vendor Number',
            type: 'tel',
            required: true,
            placeholder: 'Enter vendor number',
          },
          {
            name: 'vendorType',
            label: 'Vendor Type',
            type: 'select',
            required: true,
            placeholder: 'Select vendor type',
            options: ['Fuel Vendor', 'Part Vendor', 'Service Vendor'],
          },
          {
            name: 'vendorAddress',
            label: 'Vendor Address',
            type: 'textarea',
            full: true,
            placeholder: 'Enter complete address',
          },
          {
            name: 'state',
            label: 'State',
            type: 'select',
            options: INDIAN_STATES,
            placeholder: 'Select state',
          },
          { name: 'city', label: 'City', type: 'text', required: true, placeholder: 'Enter city' },
          {
            name: 'pincode',
            label: 'Pincode',
            type: 'text',
            placeholder: 'Enter pincode',
          },
          {
            name: 'gstNumber',
            label: 'Gst Number',
            type: 'text',
            placeholder: 'Enter GST number',
          },
          {
            name: 'remarks',
            label: 'Remarks',
            type: 'textarea',
            full: true,
            placeholder: 'Add vendor notes',
          },
        ],
      },
      {
        title: 'Bank information',
        description: 'Store payment details for the vendor.',
        fields: [
          { name: 'bankName', label: 'Bank Name', type: 'text', placeholder: 'Enter bank name' },
          {
            name: 'bankBranchName',
            label: 'Bank Branch Name',
            type: 'text',
            placeholder: 'Enter branch name',
          },
          {
            name: 'accountNumber',
            label: 'Account Number',
            type: 'text',
            placeholder: 'Enter account number',
          },
          {
            name: 'ifscCode',
            label: 'IFSC Code',
            type: 'text',
            placeholder: 'Enter IFSC code',
          },
        ],
      },
    ],
    seed: [
      {
        id: 'vendor-demo-1',
        vendorName: 'Demo Fuel Vendor',
        vendorNumber: '+91 00000 60001',
        vendorType: 'Fuel Vendor',
        vendorAddress: 'Plot 1, Demo Fuel Lane',
        state: 'Maharashtra',
        city: 'Mumbai',
        pincode: '400000',
        gstNumber: 'DEMO-VGST-0001',
        remarks: 'Fictional fuel supplier.',
        bankName: 'Demo Cooperative Bank',
        bankBranchName: 'Sample Branch',
        accountNumber: 'DEMO-VENDOR-ACCOUNT-001',
        ifscCode: 'DEMO0000101',
      },
      {
        id: 'vendor-demo-2',
        vendorName: 'Sample Parts Vendor',
        vendorNumber: '+91 00000 60002',
        vendorType: 'Part Vendor',
        vendorAddress: 'Unit 2, Sample Motor Market',
        state: 'Maharashtra',
        city: 'Pune',
        pincode: '411000',
        gstNumber: 'DEMO-VGST-0002',
        remarks: 'Fictional parts supplier.',
        bankName: 'Sample Urban Bank',
        bankBranchName: 'Demo Branch',
        accountNumber: 'DEMO-VENDOR-ACCOUNT-002',
        ifscCode: 'DEMO0000102',
      },
    ],
  },

  fuel: {
    key: 'fuel',
    path: '/fuel',
    singular: 'Fuel Entry',
    plural: 'Fuel Entries',
    description: 'Track fuel purchases, odometer readings, payments, and receipts.',
    addLabel: 'Add Fuel',
    view: false,
    searchable: ['vehicleNumber', 'vendor', 'reference', 'paymentMethod', 'fuelTank'],
    columns: [
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'vehicleNumber', label: 'Vehicle Number', primary: true },
      { key: 'odometerReading', label: 'Odometer Reading', format: 'number' },
      { key: 'liters', label: 'Liters', format: 'number' },
      { key: 'vendor', label: 'Vendor' },
      { key: 'totalAmount', label: 'Amount', format: 'currency' },
    ],
    sections: [
      {
        title: 'Fuel entry',
        description: 'Record the vehicle, vendor, quantity, and cost.',
        fields: [
          { name: 'date', label: 'Date', type: 'date', required: true },
          {
            name: 'vehicleNumber',
            label: 'Vehicle Number',
            type: 'select',
            required: true,
            placeholder: 'Select vehicle',
            options: DEMO_VEHICLES,
          },
          {
            name: 'odometerReading',
            label: 'Odometer Reading',
            type: 'number',
            required: true,
            placeholder: 'Enter odometer reading',
          },
          {
            name: 'vendor',
            label: 'Vendor',
            type: 'select',
            required: true,
            placeholder: 'Select vendor',
            options: DEMO_VENDORS,
          },
          {
            name: 'liters',
            label: 'Liter',
            type: 'number',
            required: true,
            placeholder: 'Enter litres',
          },
          {
            name: 'pricePerUnit',
            label: 'Price/Unit',
            type: 'number',
            required: true,
            placeholder: 'Enter unit price',
          },
          {
            name: 'totalAmount',
            label: 'Total Amount',
            type: 'number',
            readOnly: true,
            help: 'Calculated from litres multiplied by price per unit.',
          },
        ],
      },
      {
        title: 'Payment and receipt',
        description: 'Add payment information, tank level, proof, and notes.',
        fields: [
          {
            name: 'reference',
            label: 'Reference',
            type: 'text',
            placeholder: 'Enter bill or transaction reference',
          },
          {
            name: 'paymentMethod',
            label: 'Payment Method',
            type: 'select',
            required: true,
            placeholder: 'Select payment method',
            options: ['Cash', 'Card', 'UPI'],
          },
          {
            name: 'fuelTank',
            label: 'Fuel Tank',
            type: 'select',
            placeholder: 'Select tank level',
            options: ['Full', 'Partial'],
          },
          {
            name: 'fuelSlipPhoto',
            label: 'Fuel Slip Photo',
            type: 'file',
            accept: 'image/*',
          },
          {
            name: 'remark',
            label: 'Remark',
            type: 'textarea',
            full: true,
            placeholder: 'Add fuel entry notes',
          },
        ],
      },
    ],
    seed: [
      {
        id: 'fuel-demo-1',
        date: '2026-09-29',
        vehicleNumber: 'DEMO-VEH-001',
        odometerReading: 48210,
        vendor: 'Demo Fuel Vendor',
        liters: 42.5,
        pricePerUnit: 92,
        totalAmount: 3910,
        reference: 'DEMO-FUEL-001',
        paymentMethod: 'UPI',
        fuelTank: 'Full',
        remark: 'Fictional fuel entry.',
      },
      {
        id: 'fuel-demo-2',
        date: '2026-10-02',
        vehicleNumber: 'DEMO-VEH-002',
        odometerReading: 23890,
        vendor: 'Demo Fuel Vendor',
        liters: 18,
        pricePerUnit: 104,
        totalAmount: 1872,
        reference: 'DEMO-FUEL-002',
        paymentMethod: 'Card',
        fuelTank: 'Partial',
        remark: 'Fictional partial refill.',
      },
    ],
  },

  issues: {
    key: 'issues',
    path: '/issues',
    singular: 'Issue',
    plural: 'Issues',
    description: 'Log vehicle issues, assign responsibility, and track urgency.',
    addLabel: 'Add Issues',
    view: false,
    searchable: ['vehicleNumber', 'priority', 'summary', 'assignedTo', 'description'],
    columns: [
      { key: 'vehicleNumber', label: 'Vehicle Number', primary: true },
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'time', label: 'Time' },
      { key: 'priority', label: 'Priority', format: 'status' },
      { key: 'summary', label: 'Summary' },
    ],
    sections: [
      {
        title: 'Issue details',
        description: 'Identify the vehicle, urgency, timing, and owner.',
        fields: [
          {
            name: 'vehicleNumber',
            label: 'Vehicle Number',
            type: 'select',
            required: true,
            placeholder: 'Select vehicle',
            options: DEMO_VEHICLES,
          },
          {
            name: 'summary',
            label: 'Summary',
            type: 'text',
            required: true,
            placeholder: 'Summarise the issue',
          },
          {
            name: 'priority',
            label: 'Priority Level',
            type: 'select',
            required: true,
            placeholder: 'Select priority',
            options: ['Low', 'Medium', 'High', 'Very High'],
          },
          { name: 'date', label: 'Date', type: 'date', required: true },
          { name: 'time', label: 'Time', type: 'time', required: true },
          {
            name: 'assignedTo',
            label: 'Assign To',
            type: 'text',
            placeholder: 'Enter assignee name or team',
          },
        ],
      },
      {
        title: 'Evidence and description',
        description: 'Attach supporting files and describe the problem.',
        fields: [
          {
            name: 'issuePhoto',
            label: 'Issue Photo',
            type: 'file',
            accept: 'image/*',
          },
          {
            name: 'issueDocument',
            label: 'Issue Document',
            type: 'file',
            accept: '.pdf,.doc,.docx,image/*',
          },
          {
            name: 'description',
            label: 'Description',
            type: 'textarea',
            required: true,
            full: true,
            placeholder: 'Describe the issue and any immediate action taken',
          },
        ],
      },
    ],
    seed: [
      {
        id: 'issue-demo-1',
        vehicleNumber: 'DEMO-VEH-001',
        summary: 'Scheduled brake inspection',
        priority: 'Medium',
        date: '2026-10-03',
        time: '10:15',
        assignedTo: 'Demo Service Team',
        description: 'Fictional inspection reminder raised after a routine driver checklist.',
      },
      {
        id: 'issue-demo-2',
        vehicleNumber: 'DEMO-VEH-003',
        summary: 'Air conditioning performance check',
        priority: 'Low',
        date: '2026-10-04',
        time: '14:30',
        assignedTo: 'Sample Workshop Team',
        description: 'Fictional comfort-related issue for interface demonstration.',
      },
    ],
  },

  invoices: {
    key: 'invoices',
    path: '/invoices',
    singular: 'Invoice',
    plural: 'Invoices',
    description: 'Prepare customer invoices with service lines, charges, tax, and totals.',
    addLabel: 'Add Invoice',
    view: true,
    searchable: ['invoiceNumber', 'clientName', 'customerId', 'vehicleNumber'],
    columns: [
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'invoiceNumber', label: 'Invoice No', primary: true },
      { key: 'clientName', label: 'Bill To' },
      { key: 'customerId', label: 'Customer ID' },
      { key: 'totalAmount', label: 'Total Amount', format: 'currency' },
    ],
    sections: [
      {
        title: 'Invoice details',
        description: 'Choose the vehicle and enter customer billing information.',
        fields: [
          { name: 'date', label: 'Date', type: 'date', required: true },
          {
            name: 'vehicleNumber',
            label: 'Vehicle Number',
            type: 'select',
            required: true,
            placeholder: 'Select vehicle',
            options: DEMO_VEHICLES,
          },
          {
            name: 'clientName',
            label: 'Client Name',
            type: 'text',
            required: true,
            placeholder: 'Enter client name',
          },
          {
            name: 'clientAddress',
            label: 'Client Address',
            type: 'textarea',
            required: true,
            full: true,
            placeholder: 'Enter the address printed on the invoice',
          },
          {
            name: 'customerId',
            label: 'Customer ID',
            type: 'text',
            readOnly: true,
            help: 'Generated or linked from the selected customer record.',
          },
          {
            name: 'invoiceNumber',
            label: 'Invoice No',
            type: 'text',
            required: true,
            placeholder: 'Enter invoice number',
          },
        ],
      },
      {
        title: 'Services',
        description: 'Add the service description, quantity, rate, and calculated amount.',
        fields: [
          {
            name: 'serviceName',
            label: 'Service',
            type: 'text',
            required: true,
            full: true,
            placeholder: 'Local duty, outstation trip, extra hours, or another service',
          },
          {
            name: 'serviceQuantity',
            label: 'Qty',
            type: 'number',
            required: true,
            placeholder: '1',
          },
          {
            name: 'serviceRate',
            label: 'Price (Rs.)',
            type: 'number',
            required: true,
            placeholder: '0.00',
          },
          {
            name: 'serviceAmount',
            label: 'Amount',
            type: 'number',
            readOnly: true,
            help: 'Calculated from quantity multiplied by price.',
          },
        ],
      },
      {
        title: 'Charges and total',
        description: 'Add driver allowance, extra distance, GST, and review invoice totals.',
        fields: [
          {
            name: 'driverDa',
            label: 'Driver DA',
            type: 'number',
            placeholder: 'Enter driver allowance',
          },
          {
            name: 'extraKmDriven',
            label: 'Extra Km Driven',
            type: 'number',
            placeholder: 'Enter extra kilometres',
          },
          {
            name: 'extraKmRate',
            label: 'Extra Km Rate',
            type: 'number',
            placeholder: 'Enter extra kilometre rate',
          },
          {
            name: 'gst',
            label: 'GST',
            type: 'number',
            placeholder: 'Enter GST percentage',
          },
          {
            name: 'subTotalAmount',
            label: 'Sub Total Amount',
            type: 'number',
            readOnly: true,
            help: 'Service amount plus driver DA and extra kilometre charges.',
          },
          {
            name: 'totalAmount',
            label: 'Total Amount',
            type: 'number',
            readOnly: true,
            help: 'Subtotal plus GST.',
          },
        ],
      },
    ],
    seed: [
      {
        id: 'invoice-demo-1',
        date: '2026-09-30',
        vehicleNumber: 'DEMO-VEH-001',
        clientName: 'Northstar Demo Mobility',
        clientAddress: 'Demo Business Park, Sample Road, Mumbai',
        customerId: 'DEMO-CUST-001',
        invoiceNumber: 'DEMO-INV-001',
        serviceName: 'Sample outstation transport service',
        serviceQuantity: 1,
        serviceRate: 18000,
        serviceAmount: 18000,
        driverDa: 1200,
        extraKmDriven: 25,
        extraKmRate: 22,
        gst: 5,
        subTotalAmount: 19750,
        totalAmount: 20737.5,
      },
      {
        id: 'invoice-demo-2',
        date: '2026-10-02',
        vehicleNumber: 'DEMO-VEH-002',
        clientName: 'Bluebird Sample Tours',
        clientAddress: 'Sample Trade Centre, Demo Avenue, Pune',
        customerId: 'DEMO-CUST-002',
        invoiceNumber: 'DEMO-INV-002',
        serviceName: 'Demo local transport duty',
        serviceQuantity: 2,
        serviceRate: 4500,
        serviceAmount: 9000,
        driverDa: 800,
        extraKmDriven: 0,
        extraKmRate: 22,
        gst: 5,
        subTotalAmount: 9800,
        totalAmount: 10290,
      },
    ],
  },

  branches: {
    key: 'branches',
    path: '/masters/branches',
    singular: 'Branch',
    plural: 'Branches',
    description: 'Configure the branches available across the admin workspace.',
    addLabel: 'Add Branch',
    view: false,
    searchable: ['branchName'],
    columns: [{ key: 'branchName', label: 'Branch Name', primary: true }],
    sections: [
      {
        title: 'Branch details',
        description: 'Enter a unique display name for the branch.',
        fields: [
          {
            name: 'branchName',
            label: 'Branch Name',
            type: 'text',
            required: true,
            full: true,
            placeholder: 'Enter branch name',
          },
        ],
      },
    ],
    seed: [
      { id: 'branch-demo-1', branchName: 'Mumbai Demo Branch' },
      { id: 'branch-demo-2', branchName: 'Pune Sample Branch' },
      { id: 'branch-demo-3', branchName: 'Bengaluru Demo Branch' },
    ],
  },

  cities: {
    key: 'cities',
    path: '/masters/cities',
    singular: 'City',
    plural: 'Cities',
    description: 'Manage city landing-page content, SEO metadata, routes, and publishing.',
    addLabel: 'Add City',
    view: false,
    searchable: ['cityName', 'slug', 'h1Title', 'seoTitle', 'status'],
    columns: [
      { key: 'cityName', label: 'City', primary: true },
      { key: 'slug', label: 'Slug' },
      { key: 'routes', label: 'Routes', format: 'number' },
      { key: 'status', label: 'Status', format: 'status' },
      { key: 'updatedAt', label: 'Updated', format: 'date' },
    ],
    sections: [
      {
        title: 'City details',
        description: 'Set the city name, order, URL slug, and page heading.',
        fields: [
          {
            name: 'cityName',
            label: 'City Name',
            type: 'text',
            required: true,
            placeholder: 'Enter city name',
          },
          {
            name: 'displayOrder',
            label: 'Display Order',
            type: 'number',
            placeholder: 'Enter display order',
          },
          {
            name: 'slug',
            label: 'Slug',
            type: 'text',
            required: true,
            placeholder: 'city-name',
          },
          {
            name: 'h1Title',
            label: 'H1 Title',
            type: 'text',
            full: true,
            placeholder: 'Enter page heading',
          },
        ],
      },
      {
        title: 'Search metadata',
        description: 'Configure title, description, keywords, canonical URL, and hero image.',
        fields: [
          {
            name: 'seoTitle',
            label: 'SEO Title',
            type: 'text',
            full: true,
            placeholder: 'Enter SEO title',
          },
          {
            name: 'metaDescription',
            label: 'Meta Description',
            type: 'textarea',
            full: true,
            placeholder: 'Enter meta description',
          },
          {
            name: 'keywords',
            label: 'Keywords',
            type: 'textarea',
            full: true,
            placeholder: 'Enter comma-separated keywords',
          },
          {
            name: 'canonicalUrl',
            label: 'Canonical URL',
            type: 'text',
            full: true,
            placeholder: 'https://example.com/city-name',
          },
          {
            name: 'heroImage',
            label: 'Hero Image Upload',
            type: 'file',
            accept: 'image/*',
            full: true,
          },
        ],
      },
      {
        title: 'Page content and publishing',
        description: 'Add HTML content, scripts, and control visibility.',
        fields: [
          {
            name: 'introHtml',
            label: 'Intro HTML',
            type: 'textarea',
            full: true,
            placeholder: 'Enter introductory HTML',
          },
          {
            name: 'bodyHtml',
            label: 'Body HTML',
            type: 'textarea',
            full: true,
            placeholder: 'Enter body HTML',
          },
          {
            name: 'faqHtml',
            label: 'FAQ HTML',
            type: 'textarea',
            full: true,
            placeholder: 'Enter FAQ HTML',
          },
          {
            name: 'headScripts',
            label: 'Head Scripts',
            type: 'textarea',
            full: true,
            placeholder: 'Enter optional head scripts',
          },
          { name: 'active', label: 'Active', type: 'checkbox' },
          { name: 'published', label: 'Published', type: 'checkbox' },
        ],
      },
    ],
    seed: [
      {
        id: 'city-demo-1',
        cityName: 'Mumbai Demo',
        displayOrder: 1,
        slug: 'mumbai-demo',
        h1Title: 'Demo Cab Services in Mumbai',
        seoTitle: 'Demo Mumbai Cab Services | Sample Fleet',
        metaDescription: 'Fictional city landing-page content used for the admin preview.',
        keywords: 'demo cabs, sample travel, mumbai demo',
        canonicalUrl: 'https://example.com/mumbai-demo',
        introHtml: '<p>Demo introduction content for the Mumbai preview page.</p>',
        bodyHtml: '<p>Sample body content for interface testing.</p>',
        faqHtml: '<p>Demo FAQ content.</p>',
        headScripts: '',
        active: true,
        published: true,
        routes: 12,
        status: 'Published',
        updatedAt: '2026-09-25',
      },
      {
        id: 'city-demo-2',
        cityName: 'Pune Sample',
        displayOrder: 2,
        slug: 'pune-sample',
        h1Title: 'Sample Cab Services in Pune',
        seoTitle: 'Sample Pune Cab Services | Demo Fleet',
        metaDescription: 'Fictional draft city content used for the admin preview.',
        keywords: 'sample cabs, demo travel, pune sample',
        canonicalUrl: 'https://example.com/pune-sample',
        introHtml: '<p>Sample introduction content for the Pune preview page.</p>',
        bodyHtml: '<p>Demo body content for interface testing.</p>',
        faqHtml: '<p>Sample FAQ content.</p>',
        headScripts: '',
        active: true,
        published: false,
        routes: 8,
        status: 'Draft',
        updatedAt: '2026-09-20',
      },
    ],
  },
}

export function getCrmModule(key) {
  return crmModules[key] || null
}
